---
  kind: pipeline
  type: docker
  name: Testando
  
  clone:
    depth: 1
    branch: $DRONE_BRANCH
    
  steps:

    - name: clone_lambinho
      image: drone/git
      commands:
        - ls -lha
